version: 1

update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"

    default_reviewers:
      - "leocomelli"
    default_assignees:
      - "leocomelli"
